name: 💡 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your needs.

  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      description: Describe the problem or pain point you're experiencing
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What solution would you like?
      description: A clear and concise description of what you want to happen
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: What alternatives have you considered?
      description: Any alternative solutions or features you've considered
      placeholder: I've considered...

  - type: dropdown
    id: feature-area
    attributes:
      label: Which area does this feature relate to?
      multiple: true
      options:
        - CLI commands and interface
        - Shop configuration and management
        - Contextual development workflow
        - Branch operations and Git integration
        - Campaign and promo management
        - Testing and quality assurance
        - Security and credential management
        - Performance and monitoring
        - Documentation and examples
        - GitHub integration and automation

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my workflow
        - Critical for adoption

  - type: textarea
    id: use-case
    attributes:
      label: Describe your use case
      description: Help us understand how you would use this feature
      placeholder: |
        I manage 5 Shopify stores and need to...
        My team of 10 developers would use this to...
        For our e-commerce client, this would enable...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information that might help us understand your needs...